### ISSUE TITLE
Paper?

### ISSUE THREAD

**Issue by wizardk** [choiHkk/CVAEJETS#3]
Hello, where is the paper corresponding to this work? Thanks.

**Comment by choiHkk** [comment]
there is no paper, it's my own project.

**Comment by wizardk** [comment]
@choiHkk Got it, thanks.
And how about the sound quality and rhythm compared with VITS?

**Comment by choiHkk** [comment]
@wizardk sorry, i didn't compare rhythm(+duration) with VITS. but you can check sound quality between CVAEJETS and VITS at each jupyter notebook script.
